# Generated by Django 3.2.3 on 2022-10-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0009_auto_20210715_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='owner',
        ),
    ]
